class PracticeOnCharDataType{
	public static void main(String[] args) {
		char ch = 'A';
		System.out.println(ch);
		ch = 'B';
		System.out.println(ch);
		ch = 65;
		System.out.println(ch);
		ch = 66;
		System.out.println(ch);
		ch = 67;
		System.out.println(ch);
		ch = 68;
		System.out.println(ch);
		ch = 69;
		System.out.println(ch);
		ch = 70;
		System.out.println(ch);
		ch = 71;
		System.out.println(ch);
		ch = 72;
		System.out.println(ch);
		ch = 73;
		System.out.println(ch);
		ch = 74;
		System.out.println(ch);
		ch = 75;
		System.out.println(ch);
		ch = 76;
		System.out.println(ch);
		ch = 77;
		System.out.println(ch);
		ch = 78;
		System.out.println(ch);
		ch = 79;
		System.out.println(ch);
		ch = 80;
		System.out.println(ch);
		ch = 81;
		System.out.println(ch);
		ch = 82;
		System.out.println(ch);
		ch = 83;
		System.out.println(ch);
		ch = 84;
		System.out.println(ch);
		ch = 85;
		System.out.println(ch);
		ch = 86;
		System.out.println(ch);
		ch = 87;
		System.out.println(ch);
		ch = 88;
		System.out.println(ch);
		ch = 89;
		System.out.println(ch);
		ch = 90;
		System.out.println(ch);
		

		ch = 97;
		System.out.println(ch);
		ch = 98;
		System.out.println(ch);
		ch = 99;
		System.out.println(ch);
		ch = 100;
		System.out.println(ch);
		ch = 101;
		System.out.println(ch);
		ch = 102;
		System.out.println(ch);
		ch = 103;
		System.out.println(ch);
		ch = 104;
		System.out.println(ch);
		ch = 105;
		System.out.println(ch);
		ch = 106;
		System.out.println(ch);
		ch = 107;
		System.out.println(ch);
		ch = 108;
		System.out.println(ch);
		ch = 109;
		System.out.println(ch);
		ch = 110;
		System.out.println(ch);
		ch = 111;
		System.out.println(ch);
		ch = 112;
		System.out.println(ch);
		ch = 113;
		System.out.println(ch);
		ch = 114;
		System.out.println(ch);
		ch = 115;
		System.out.println(ch);
		ch = 116;
		System.out.println(ch);
		ch = 117;
		System.out.println(ch);
		ch = 118;
		System.out.println(ch);
		ch = 119;
		System.out.println(ch);
		ch = 120;
		System.out.println(ch);
		ch = 121;
		System.out.println(ch);
		ch = 122;
		System.out.println(ch);
		
	}
}